[features]
seeds = false
skip-lint = false
[programs.localnet]
verifiable_build = "AD62W7aAQETg11ajkadk57DYfPTWPzKLiXuLZVB4eQaw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/devenv/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
